version: '3.5'

services:
  postgres:
    container_name: postgres_postgres
    image: postgres
    restart: unless-stopped
    networks:
      - example_net
    environment:
      POSTGRES_USER: product
      POSTGRES_PASSWORD: product
      POSTGRES_DB: product
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgres-data:/var/lib/postgresql/data
  golang:
    image: golang:latest
    command: 'go run .'
    networks:
      - example_net
    tty: true
    working_dir: /var/www
    restart: always
    volumes:
      - ./:/var/www
    ports:
      - "3000:3000"
      - "5555:5555"
networks:
  example_net:
    name: example_net